#CI Nível 04 - Disparo dentro do fluxo de CI de Desenvolvimento

name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencies
        run: yarn

      - name: Lint / Prettier (Padronização de Código)
        run: yarn lint

  unit:
    runs-on: ubuntu-latest
    needs: [inspection]
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencies
        run: yarn

      - name: Testes de Unidade
        run: yarn run test

  e2e-testes:
    runs-on: ubuntu-latest
    needs: [unit]
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencies
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Subir a aplicação local no localhost 3000
        run: yarn start &

      - name: Testes E2E
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000' #não pode ter a barra no final

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: tests_reports
          path: ./playwright-report

  deploy:
    runs-on: ubuntu-latest
    needs: [e2e-testes]
    steps:
      - name: Deploy
        run: echo "step deploy"